spring:
  datasource:
    url: jdbc:mysql://localhost:3306/flutter?useUnicode=true&characterEncoding=UTF-8&serverTimezone=CST&useSSL=false&allowPublicKeyRetrieval=true
    username: flutter
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 9094